/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=deploy/cloudflare/wrangler.jsonc --include-runtime=false adapters/worker/worker-configuration.d.ts` (hash: 46256fbdf2c85f35883a9344ecb2c3f1)
interface __BaseEnv_Env {
  INTERNAL_HMAC_SECRET: string;
  ROOMS: DurableObjectNamespace<import('./worker').RoomDurableObject>;
  ADMISSION: DurableObjectNamespace<import('./worker').AdmissionLimiterDurableObject>;
  TOKEN_ISSUERS: DurableObjectNamespace<import('./worker').TokenIssuerDurableObject>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker');
    durableNamespaces:
      'RoomDurableObject' | 'AdmissionLimiterDurableObject' | 'TokenIssuerDurableObject';
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
